### PR TITLE
Contact form validation js

### PR DESCRIPTION
**Pull request by adelphinsucasa**
- Add Contact Form Validation with Javascript, content of the email field has to be in lowercase
- Update Readme Features

### CODE REVIEW

**Review by Gambit142 — COMMENTED** [review]
Hi @adelphinsucasa @chelobotix 👋 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- You have submitted a project, that the JavaScript linter (Eslint) was not set up. Kindly set it up. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by adelphinsucasa** [comment]
> Hi @adelphinsucasa @chelobotix 👋 ,
> 
> While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
> 
> ## Invalid Code Review Request
> * You have submitted a project, that the JavaScript linter (Eslint) was not set up. Kindly set it up.
> 
> Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _Invalid Code Review Request **does not count** into the code reviews limit._

Hi Gambit142
Thank you for your review. I am wondering why this problem is presented. I installed Eslint, and I use this sentence to check " npx eslint . --fix" 
Once  I dindt get errors I did the commit. 
Can you guide me please about this observation please, I mean why we are not getting Eslint. Please check the use in this picture on my local machine.
[EslintInstalled.jpg](https://drive.google.com/file/d/1zAabaqcqIPG0DQTOnckZHSuZmhfOGnsJ/view?usp=share_link)

**Comment by adelphinsucasa** [comment]
> > Hi @adelphinsucasa @chelobotix 👋 ,
> > While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
> > ## Invalid Code Review Request
> > 
> > * You have submitted a project, that the JavaScript linter (Eslint) was not set up. Kindly set it up.
> > 
> > Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
> > Cheers and Happy coding!👏👏👏
> > Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> > **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> > _Invalid Code Review Request **does not count** into the code reviews limit._
> 
> Hi Gambit142 Thank you for your review. I am wondering why this problem is presented. I installed Eslint, and I use this sentence to check " npx eslint . --fix" Once I dindt get errors I did the commit. Can you guide me please about this observation please, I mean why we are not getting Eslint. Please check the use in this picture on my local machine. [EslintInstalled.jpg](https://drive.google.com/file/d/1zAabaqcqIPG0DQTOnckZHSuZmhfOGnsJ/view?usp=share_link)

Also if you check in the code section, you can find .eslintrc.json file it was mounted 4 days ago.

**Comment by Gopxfs** [comment]
Hello @adelphinsucasa, please make sure to follow [this linters setup](https://github.com/microverseinc/linters-config/tree/master/html-css-js) 😉. It is a different linter setup for JS + HTML + CSS, instead of only HTML + CSS. Kindly notice that your `linters.yml` inside the `.github/workflows` folder doesn't contain the ESlint config.

**Comment by Gopxfs** [comment]
# STATUS: INVALID REQUEST

Hi 👋,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### You have submitted a project that doesn't contain the ESlint setup correctly.

Your Code Review Request will be marked invalid in your Dashboard, so please submit a new one once ready 🙏.
Invalid requests don't count as a review, so don't worry about that 😄!

Cheers and Happy coding!👏👏👏

--------

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Gopxfs in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by adelphinsucasa** [comment]
> Hello @adelphinsucasa, please make sure to follow [this linters setup](https://github.com/microverseinc/linters-config/tree/master/html-css-js) 😉. It is a different linter setup for JS + HTML + CSS, instead of only HTML + CSS. Kindly notice that your `linters.yml` inside the `.github/workflows` folder doesn't contain the ESlint config.

Thank you very much. I had to uninstall everything remove nodemodules and reinstall everything, and now is working

**Comment by Gambit142** [comment]
> > Hi @adelphinsucasa @chelobotix 👋 ,
> > While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
> > ## Invalid Code Review Request
> > 
> > * You have submitted a project, that the JavaScript linter (Eslint) was not set up. Kindly set it up.
> > 
> > Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
> > Cheers and Happy coding!👏👏👏
> > Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> > **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> > _Invalid Code Review Request **does not count** into the code reviews limit._
> 
> Hi Gambit142 Thank you for your review. I am wondering why this problem is presented. I installed Eslint, and I use this sentence to check " npx eslint . --fix" Once I dindt get errors I did the commit. Can you guide me please about this observation please, I mean why we are not getting Eslint. Please check the use in this picture on my local machine. [EslintInstalled.jpg](https://drive.google.com/file/d/1zAabaqcqIPG0DQTOnckZHSuZmhfOGnsJ/view?usp=share_link)

Hi @adelphinsucasa, sorry for the late reply but I see you have fixed it. Great work 💪

**Review by Gambit142 — APPROVED** [review]
Hi @adelphinsucasa @chelobotix 👋,

## Status: Approved 🟢   

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

### Highlights
- All linters checks passed ✔️ 
- Email Validation functions properly ✔️ 
- Uses the `submit` `eventListener` ✔️ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
